-- MySQL Script generated by MySQL Workbench
-- seg 01 mar 2021 10:40:42
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PHPtest
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PHPtest
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PHPtest` ;
USE `PHPtest` ;

-- -----------------------------------------------------
-- Table `PHPtest`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PHPtest`.`address` (
  `cep` VARCHAR(9) NOT NULL,
  `logradouro` VARCHAR(100) NULL,
  `complemento` VARCHAR(150) NULL,
  `bairro` VARCHAR(100) NULL,
  `localidade` VARCHAR(50) NULL,
  `uf` VARCHAR(3) NULL,
  `ibge` VARCHAR(45) NULL,
  `gia` VARCHAR(45) NULL,
  `ddd` VARCHAR(45) NULL,
  `siafi` VARCHAR(45) NULL,
  PRIMARY KEY (`cep`),
  UNIQUE INDEX `cep_UNIQUE` (`cep` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
